[package]
name = "typeward"
version = "0.2.0"
edition = "2024"

[dependencies]
array-util = { version = "1.0", optional = true }
pastey = "0.2"
stable-pattern = { version = "0.1", default-features = false }
typeward-macros = { path = "crates/typeward-macros", optional = true }

[features]
default = ["arrays", "macros"]
arrays = ["dep:array-util"]
macros = ["typeward-macros"]

[workspace]
members = ["crates/typeward-macros", "examples/json"]
