[package]
name = "typeward-macros"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Procedural macros for the Typeward parser combinator library."
repository = "https://github.com/Exotik850/typeward"
keywords = ["macro", "typeward", "parser combinator", "rust"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false }
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
typeward = { path = "../..", version = "*", default-features = false }
